apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: {{ .Values.webName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.webName }}
  template:
    metadata:
      labels:
        app: {{ .Values.webName }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webService }}
spec:
  selector:
    app: {{ .Values.webName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
